name: hpiwf
description: "AIoT ecosystem for the Elderly & Alzheimer's patients"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_gauges: ^34.2.3
  stroke_text: ^1.0.0
  intl: ^0.20.3
  mqtt_client: ^10.11.11
  flutter_onnxruntime: ^1.8.4
  firebase_core: ^4.14.0
  flutter_dotenv: ^6.0.1
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0
  toastification: ^3.2.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  drop_shadow: ^0.1.0
  spoiler_widget: ^1.0.25
  url_launcher: ^6.3.2
  image_picker: ^1.2.3
  flutter_local_notifications: ^22.3.1
  shared_preferences: ^2.5.5
  rename_app: ^1.6.6
  firebase_messaging: ^16.7.0
  firebase_app_installations: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_rename_app:
  application_name: "HPiwf Controller"

flutter_launcher_icons:
  image_path: "assets/app-icon.png"
  android: true
  ios: true

  web:
    generate: true
    image_path: "assets/app-icon.png"
    background_color: "#04040c"
    theme_color: "#81acd9"

  windows:
    generate: true
    image_path: "assets/app-icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/app-icon.png"

  linux:
    generate: true
    image_path: "assets/app-icon.png"


flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/ML-models/
 
  fonts:
    - family: cubano
      fonts:
        - asset: fonts/cubano.otf

    - family: oldstyle
      fonts:
        - asset: fonts/oldstyle.ttf