name: Deploy Flutter Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create secret files
        run: |
          mkdir -p app/lib
          echo '${{ secrets.HPIWF_SECRETS }}' > app/secrets.json
          echo '${{ secrets.FIREBASE_OPTIONS_FILE }}' | base64 -d > app/lib/firebase_options.dart

      - name: Build Web
        run: |
          cd app
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable flutter
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get
          flutter build web --dart-define-from-file=secrets.json

      - name: Deploy to Vercel
        run: |
          cd app
          npx vercel@latest deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}